# Common
#
USERCOUNT=3
INFRA_PROJECT=lab-infra

# Homeroom
#
HR_PROJECT=$INFRA_PROJECT

# Get a Username
#
GAU_PROJECT=$INFRA_PROJECT
GAU_ACCESS_TOKEN=openshift2021
GAU_ADMIN_PASSWORD=mysecretgaupassword